on:
  workflow_dispatch:

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo "Hello World from Windows Runner!!"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Cloning GitHub Repo 
        uses: actions/checkout@v3
      - name: List files in workspace
        run: dir ${{ github.workspace }}
      - name: Print all Environment Variables
        run: SET
        shell: cmd
